AUDIO_DATA_PATH = '../../GRIDDATA/audio'
VIDEO_DATA_PATH = '../../GRIDDATA/resized'

# Audio Encoder

SEQ_LEN = 1
AUDIO_OUTPUT = 256
HIDDEN_SIZE_AUDIO = 256
NUM_LAYERS_AUDIO = 2

# Noise Encoder

NOISE_OUTPUT = 10
BATCH = 38
HIDDEN_SIZE_NOISE = 10
NUM_LAYERS_NOISE = 1

# TRAINING PARAMS

learning_rate = 0.000001